volumes:
  mongodb_data:

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: ${DATABASE_URL}
      SIGNING_KEY: ${SIGNING_KEY}
      MONGO_DB: ${MONGO_DB}
      INDEX_DB_NAME: "indexdir"
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8030:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3030:3000"
    environment:
       HOST_OS: ${OS}
       NODE_ENV: development
       HOST: "0.0.0.0"
       VITE_PUBLIC_URL: ""
       VITE_API_HOST: ${VITE_API_HOST}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: quantumcup

